# Generated by Django 5.1.1 on 2024-09-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('departure', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=10, unique=True, verbose_name='Бортовой номер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.client', verbose_name='Клиент')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('baggage_type', models.CharField(max_length=50, verbose_name='Тип багажа')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багажи',
            },
        ),
    ]
