# Generated by Django 5.1.1 on 2024-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_client_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='picture',
            field=models.ImageField(null=True, upload_to='airplane', verbose_name='Изображение'),
        ),
    ]
