# Generated by Django 5.1.1 on 2024-12-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
